version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "07:00"
    open-pull-requests-limit: 10
    reviewers:
      - weirdan
    labels:
      - dependencies
  - package-ecosystem: github-actions
    directory: /
    schedule:
      timezone: UTC
      interval: monthly
    open-pull-requests-limit: 10
    reviewers:
      - weirdan
    labels:
      - dependencies
