name: Deploy to Heroku
on: 
  release:
    types:
      - released
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git checkout heroku
          git reset --hard ${{ github.ref }}
          git push --force
